### ISSUE TITLE
Adding to existing ingredients concatenates amount instead of adding

### ISSUE THREAD

**Issue by bencalabrese** [cheshirekate8/queenOfSauce#13]
When on the ingredients page, selecting more of an existing ingredient concatenates the new amount instead of adding it.

ex. with 3 potatoes, adding 5 more results in 35 in the fridge instead of the expected 8

https://user-images.githubusercontent.com/15733293/135783706-7ebb9214-82aa-4752-9b66-ba3ee2caf61c.mp4

.

**Comment by cheshirekate8** [comment]
Fixed! Problem was that the form was returning a string instead of a number. Just wrapped the quantity returned from the form in a Number() function and error resolved! Thanks a bunch! ^_^
